#!/bin/sh

### BEGIN INIT INFO
# Provides:          exampledaemon
# Required-Start:    $local_fs $remote_fs $network $time postgresql
# Required-Stop:     $local_fs $remote_fs $network $time
# Should-Start:      $syslog
# Should-Stop:       $syslog postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Keter web-server
# Description:       Keter web-server start-stop-daemon
### END INIT INFO

# This is an example of a sysvinit script for keter web server
# (init.d service in Ubuntu/Debian)
# Users of keter (https://github.com/snoyberg/keter) under Ubuntu:
#   After quick start, just copy this file into "/etc/init.d" and run:
#   sudo update-rc.d keterdaemon defaults
# Thanks for the template goes to Jonas Friedmann (https://github.com/frdmn)
#   https://raw.github.com/frdmn/service-daemons/master/debian
#   http://blog.frd.mn/how-to-set-up-proper-startstop-services-ubuntu-debian-mac-windows/

NAME="keter"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/opt/keter/"
APPBIN="/opt/keter/bin/keter"
APPARGS="/opt/keter/etc/keter-config.yaml"
USER="root"
GROUP="keter"

# Include functions
set -e
. /lib/lsb/init-functions

start() {
  printf "Starting '$NAME'... "
  start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/$NAME.pid --chdir "$APPDIR" --exec "$APPBIN" -- $APPARGS || true
  printf "done\n"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
  printf "Stopping '$NAME'... "
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
  while test -d /proc/$(cat /var/run/$NAME.pid); do
    killtree $(cat /var/run/$NAME.pid) 15
    sleep 0.5
  done
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
  printf "done\n"
}

status() {
  status_of_proc -p /var/run/$NAME.pid "" $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
