-----------------------------------------------------------------------------
-- |
-- Module      :  InsertCountries
-- Copyright   :  (c) Artem Chirkin
-- License     :  BSD3
--
-- Maintainer  :  Artem Chirkin <chirkin@arch.ethz.ch>
-- Stability   :  experimental
--
-- Hard-coded country fields
-----------------------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}

module InsertCountries
    ( insertCountries
    ) where

import Model
import Database.Persist
import Control.Monad.Trans.Reader (ReaderT)
import Data.Text (Text)
import Data.Map (Map)
import qualified Data.Map as Map

chunk :: Int
chunk = 10

-- | Import a hardcoded list of countries
insertCountries :: ReaderT (PersistEntityBackend Country) IO (Map Text CountryId)
insertCountries = do
    deleteWhere ([] :: [Filter Country])
    mapM_ insertMany_ $ let f [] = []
                            f xs = case splitAt chunk xs of
                                     ([],[]) -> []
                                     ( a,[]) -> a : []
                                     ( a, b) -> a : f b
                        in f countries
    Map.fromList . fmap isoId <$> selectList [] []
  where isoId (Entity i Country{countryIso = c}) = (c,i)

countries :: [Country]
countries =
  [ Country "AA" "AW" ".aw" "Aruba"
  , Country "AC" "AG" ".ag" "Antigua and Barbuda"
  , Country "AE" "AE" ".ae" "United Arab Emirates"
  , Country "AF" "AF" ".af" "Afghanistan"
  , Country "AG" "DZ" ".dz" "Algeria"
  , Country "AJ" "AZ" ".az" "Azerbaijan"
  , Country "AL" "AL" ".al" "Albania"
  , Country "AM" "AM" ".am" "Armenia"
  , Country "AN" "AD" ".ad" "Andorra"
  , Country "AO" "AO" ".ao" "Angola"
  , Country "AQ" "AS" ".as" "American Samoa"
  , Country "AR" "AR" ".ar" "Argentina"
  , Country "AS" "AU" ".au" "Australia"
  , Country "AU" "AT" ".at" "Austria"
  , Country "AV" "AI" ".ai" "Anguilla"
  , Country "AX" "AX" ".ax" "Aland Islands"
  , Country "AY" "AQ" ".aq" "Antarctica"
  , Country "BA" "BH" ".bh" "Bahrain"
  , Country "BB" "BB" ".bb" "Barbados"
  , Country "BC" "BW" ".bw" "Botswana"
  , Country "BD" "BM" ".bm" "Bermuda"
  , Country "BE" "BE" ".be" "Belgium"
  , Country "BF" "BS" ".bs" "Bahamas The"
  , Country "BG" "BD" ".bd" "Bangladesh"
  , Country "BH" "BZ" ".bz" "Belize"
  , Country "BK" "BA" ".ba" "Bosnia and Herzegovina"
  , Country "BL" "BO" ".bo" "Bolivia"
  , Country "BM" "MM" ".mm" "Myanmar"
  , Country "BN" "BJ" ".bj" "Benin"
  , Country "BO" "BY" ".by" "Belarus"
  , Country "BP" "SB" ".sb" "Solomon Islands"
  , Country "BR" "BR" ".br" "Brazil"
  , Country "BT" "BT" ".bt" "Bhutan"
  , Country "BU" "BG" ".bg" "Bulgaria"
  , Country "BV" "BV" ".bv" "Bouvet Island"
  , Country "BX" "BN" ".bn" "Brunei"
  , Country "BY" "BI" ".bi" "Burundi"
  , Country "CA" "CA" ".ca" "Canada"
  , Country "CB" "KH" ".kh" "Cambodia"
  , Country "CD" "TD" ".td" "Chad"
  , Country "CE" "LK" ".lk" "Sri Lanka"
  , Country "CF" "CG" ".cg" "Congo Republic of the"
  , Country "CG" "CD" ".cd" "Congo Democratic Republic of the"
  , Country "CH" "CN" ".cn" "China"
  , Country "CI" "CL" ".cl" "Chile"
  , Country "CJ" "KY" ".ky" "Cayman Islands"
  , Country "CK" "CC" ".cc" "Cocos (Keeling) Islands"
  , Country "CM" "CM" ".cm" "Cameroon"
  , Country "CN" "KM" ".km" "Comoros"
  , Country "CO" "CO" ".co" "Colombia"
  , Country "CQ" "MP" ".mp" "Northern Mariana Islands"
  , Country "CS" "CR" ".cr" "Costa Rica"
  , Country "CT" "CF" ".cf" "Central African Republic"
  , Country "CU" "CU" ".cu" "Cuba"
  , Country "CV" "CV" ".cv" "Cape Verde"
  , Country "CW" "CK" ".ck" "Cook Islands"
  , Country "CY" "CY" ".cy" "Cyprus"
  , Country "DA" "DK" ".dk" "Denmark"
  , Country "DJ" "DJ" ".dj" "Djibouti"
  , Country "DO" "DM" ".dm" "Dominica"
  , Country "DR" "DO" ".do" "Dominican Republic"
  , Country "EC" "EC" ".ec" "Ecuador"
  , Country "EG" "EG" ".eg" "Egypt"
  , Country "EI" "IE" ".ie" "Ireland"
  , Country "EK" "GQ" ".gq" "Equatorial Guinea"
  , Country "EN" "EE" ".ee" "Estonia"
  , Country "ER" "ER" ".er" "Eritrea"
  , Country "ES" "SV" ".sv" "El Salvador"
  , Country "ET" "ET" ".et" "Ethiopia"
  , Country "EZ" "CZ" ".cz" "Czech Republic"
  , Country "FG" "GF" ".gf" "French Guiana"
  , Country "FI" "FI" ".fi" "Finland"
  , Country "FJ" "FJ" ".fj" "Fiji"
  , Country "FK" "FK" ".fk" "Falkland Islands (Islas Malvinas)"
  , Country "FM" "FM" ".fm" "Micronesia Federated States of"
  , Country "FO" "FO" ".fo" "Faroe Islands"
  , Country "FP" "PF" ".pf" "French Polynesia"
  , Country "FR" "FR" ".fr" "France"
  , Country "FS" "TF" ".tf" "French Southern and Antarctic Lands"
  , Country "GA" "GM" ".gm" "Gambia The"
  , Country "GB" "GA" ".ga" "Gabon"
  , Country "GG" "GE" ".ge" "Georgia"
  , Country "GH" "GH" ".gh" "Ghana"
  , Country "GI" "GI" ".gi" "Gibraltar"
  , Country "GJ" "GD" ".gd" "Grenada"
  , Country "GL" "GL" ".gl" "Greenland"
  , Country "GM" "DE" ".de" "Germany"
  , Country "GP" "GP" ".gp" "Guadeloupe"
  , Country "GQ" "GU" ".gu" "Guam"
  , Country "GR" "GR" ".gr" "Greece"
  , Country "GT" "GT" ".gt" "Guatemala"
  , Country "GV" "GN" ".gn" "Guinea"
  , Country "GY" "GY" ".gy" "Guyana"
  , Country "HA" "HT" ".ht" "Haiti"
  , Country "HK" "HK" ".hk" "Hong Kong"
  , Country "HM" "HM" ".hm" "Heard Island and McDonald Islands"
  , Country "HO" "HN" ".hn" "Honduras"
  , Country "HR" "HR" ".hr" "Croatia"
  , Country "HU" "HU" ".hu" "Hungary"
  , Country "IC" "IS" ".is" "Iceland"
  , Country "ID" "ID" ".id" "Indonesia"
  , Country "IM" "IM" ".im" "Isle of Man"
  , Country "IN" "IN" ".in" "India"
  , Country "IO" "IO" ".io" "British Indian Ocean Territory"
  , Country "IR" "IR" ".ir" "Iran"
  , Country "IS" "IL" ".il" "Israel"
  , Country "IT" "IT" ".it" "Italy"
  , Country "IV" "CI" ".ci" "Cote d'Ivoire"
  , Country "IZ" "IQ" ".iq" "Iraq"
  , Country "JA" "JP" ".jp" "Japan"
  , Country "JE" "JE" ".je" "Jersey"
  , Country "JM" "JM" ".jm" "Jamaica"
  , Country "JO" "JO" ".jo" "Jordan"
  , Country "KE" "KE" ".ke" "Kenya"
  , Country "KG" "KG" ".kg" "Kyrgyzstan"
  , Country "KN" "KP" ".kp" "Korea North"
  , Country "KR" "KI" ".ki" "Kiribati"
  , Country "KS" "KR" ".kr" "Korea South"
  , Country "KT" "CX" ".cx" "Christmas Island"
  , Country "KU" "KW" ".kw" "Kuwait"
  , Country "KZ" "KZ" ".kz" "Kazakhstan"
  , Country "LA" "LA" ".la" "Laos"
  , Country "LE" "LB" ".lb" "Lebanon"
  , Country "LG" "LV" ".lv" "Latvia"
  , Country "LH" "LT" ".lt" "Lithuania"
  , Country "LI" "LR" ".lr" "Liberia"
  , Country "LO" "SK" ".sk" "Slovakia"
  , Country "LS" "LI" ".li" "Liechtenstein"
  , Country "LT" "LS" ".ls" "Lesotho"
  , Country "LU" "LU" ".lu" "Luxembourg"
  , Country "LY" "LY" ".ly" "Libyan Arab"
  , Country "MA" "MG" ".mg" "Madagascar"
  , Country "MB" "MQ" ".mq" "Martinique"
  , Country "MC" "MO" ".mo" "Macau"
  , Country "MD" "MD" ".md" "Moldova Republic of"
  , Country "MF" "YT" ".yt" "Mayotte"
  , Country "MG" "MN" ".mn" "Mongolia"
  , Country "MH" "MS" ".ms" "Montserrat"
  , Country "MI" "MW" ".mw" "Malawi"
  , Country "MJ" "ME" ".me" "Montenegro"
  , Country "MK" "MK" ".mk" "The Former Yugoslav Republic of Macedonia"
  , Country "ML" "ML" ".ml" "Mali"
  , Country "MN" "MC" ".mc" "Monaco"
  , Country "MO" "MA" ".ma" "Morocco"
  , Country "MP" "MU" ".mu" "Mauritius"
  , Country "MR" "MR" ".mr" "Mauritania"
  , Country "MT" "MT" ".mt" "Malta"
  , Country "MU" "OM" ".om" "Oman"
  , Country "MV" "MV" ".mv" "Maldives"
  , Country "MX" "MX" ".mx" "Mexico"
  , Country "MY" "MY" ".my" "Malaysia"
  , Country "MZ" "MZ" ".mz" "Mozambique"
  , Country "NC" "NC" ".nc" "New Caledonia"
  , Country "NE" "NU" ".nu" "Niue"
  , Country "NF" "NF" ".nf" "Norfolk Island"
  , Country "NG" "NE" ".ne" "Niger"
  , Country "NH" "VU" ".vu" "Vanuatu"
  , Country "NI" "NG" ".ng" "Nigeria"
  , Country "NL" "NL" ".nl" "Netherlands"
  , Country "NO" "NO" ".no" "Norway"
  , Country "NP" "NP" ".np" "Nepal"
  , Country "NR" "NR" ".nr" "Nauru"
  , Country "NS" "SR" ".sr" "Suriname"
  , Country "NT" "AN" ".an" "Netherlands Antilles"
  , Country "NU" "NI" ".ni" "Nicaragua"
  , Country "NZ" "NZ" ".nz" "New Zealand"
  , Country "PA" "PY" ".py" "Paraguay"
  , Country "PC" "PN" ".pn" "Pitcairn Islands"
  , Country "PE" "PE" ".pe" "Peru"
  , Country "PK" "PK" ".pk" "Pakistan"
  , Country "PL" "PL" ".pl" "Poland"
  , Country "PM" "PA" ".pa" "Panama"
  , Country "PO" "PT" ".pt" "Portugal"
  , Country "PP" "PG" ".pg" "Papua New Guinea"
  , Country "PS" "PW" ".pw" "Palau"
  , Country "PU" "GW" ".gw" "Guinea-Bissau"
  , Country "QA" "QA" ".qa" "Qatar"
  , Country "RE" "RE" ".re" "Reunion"
  , Country "RI" "RS" ".rs" "Serbia"
  , Country "RM" "MH" ".mh" "Marshall Islands"
  , Country "RN" "MF" "-"   "Saint Martin"
  , Country "RO" "RO" ".ro" "Romania"
  , Country "RP" "PH" ".ph" "Philippines"
  , Country "RQ" "PR" ".pr" "Puerto Rico"
  , Country "RS" "RU" ".ru" "Russia"
  , Country "RW" "RW" ".rw" "Rwanda"
  , Country "SA" "SA" ".sa" "Saudi Arabia"
  , Country "SB" "PM" ".pm" "Saint Pierre and Miquelon"
  , Country "SC" "KN" ".kn" "Saint Kitts and Nevis"
  , Country "SE" "SC" ".sc" "Seychelles"
  , Country "SF" "ZA" ".za" "South Africa"
  , Country "SG" "SN" ".sn" "Senegal"
  , Country "SH" "SH" ".sh" "Saint Helena"
  , Country "SI" "SI" ".si" "Slovenia"
  , Country "SL" "SL" ".sl" "Sierra Leone"
  , Country "SM" "SM" ".sm" "San Marino"
  , Country "SN" "SG" ".sg" "Singapore"
  , Country "SO" "SO" ".so" "Somalia"
  , Country "SP" "ES" ".es" "Spain"
  , Country "ST" "LC" ".lc" "Saint Lucia"
  , Country "SU" "SD" ".sd" "Sudan"
  , Country "SV" "SJ" ".sj" "Svalbard and Jan Mayen"
  , Country "SW" "SE" ".se" "Sweden"
  , Country "SX" "GS" ".gs" "South Georgia and the Islands"
  , Country "SY" "SY" ".sy" "Syrian Arab Republic"
  , Country "SZ" "CH" ".ch" "Switzerland"
  , Country "TD" "TT" ".tt" "Trinidad and Tobago"
  , Country "TH" "TH" ".th" "Thailand"
  , Country "TI" "TJ" ".tj" "Tajikistan"
  , Country "TK" "TC" ".tc" "Turks and Caicos Islands"
  , Country "TL" "TK" ".tk" "Tokelau"
  , Country "TN" "TO" ".to" "Tonga"
  , Country "TO" "TG" ".tg" "Togo"
  , Country "TP" "ST" ".st" "Sao Tome and Principe"
  , Country "TS" "TN" ".tn" "Tunisia"
  , Country "TT" "TL" ".tl" "East Timor"
  , Country "TU" "TR" ".tr" "Turkey"
  , Country "TV" "TV" ".tv" "Tuvalu"
  , Country "TW" "TW" ".tw" "Taiwan"
  , Country "TX" "TM" ".tm" "Turkmenistan"
  , Country "TZ" "TZ" ".tz" "Tanzania United Republic of"
  , Country "UG" "UG" ".ug" "Uganda"
  , Country "UK" "GB" ".uk" "United Kingdom"
  , Country "UP" "UA" ".ua" "Ukraine"
  , Country "US" "US" ".us" "United States"
  , Country "UV" "BF" ".bf" "Burkina Faso"
  , Country "UY" "UY" ".uy" "Uruguay"
  , Country "UZ" "UZ" ".uz" "Uzbekistan"
  , Country "VC" "VC" ".vc" "Saint Vincent and the Grenadines"
  , Country "VE" "VE" ".ve" "Venezuela"
  , Country "VI" "VG" ".vg" "British Virgin Islands"
  , Country "VM" "VN" ".vn" "Vietnam"
  , Country "VQ" "VI" ".vi" "Virgin Islands (US)"
  , Country "VT" "VA" ".va" "Holy See (Vatican City)"
  , Country "WA" "NA" ".na" "Namibia"
  , Country "WF" "WF" ".wf" "Wallis and Futuna"
  , Country "WI" "EH" ".eh" "Western Sahara"
  , Country "WS" "WS" ".ws" "Samoa"
  , Country "WZ" "SZ" ".sz" "Swaziland"
  , Country "YI" "CS" ".yu" "Serbia and Montenegro"
  , Country "YM" "YE" ".ye" "Yemen"
  , Country "ZA" "ZM" ".zm" "Zambia"
  , Country "ZI" "ZW" ".zw" "Zimbabwe"
  , Country "DQ" "UM" "-"   "United States Minor Outlying Islands"
  , Country "KV" "XK" "-"   "Kosovo"
  , Country "OD" "SS" ".ss" "South Sudan"
  , Country "WE" "PS" ".ps" "Palestine"
  , Country "UC" "CW" "-"   "Curacao"
  , Country "NN" "SX" ".sx" "Sint Maarten"
  , Country "GK" "GG" "-"   "Guernsey"
  , Country "--" "BQ" "-"   "Bonaire"
  , Country "TB" "BL" "-"   "Saint Barthélemy"
  ]
